apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath  # Add this line to match the PVC's StorageClass
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/mongo
