version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  webapp:
    build: .
    container_name: node-webapp
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://admin:password@mongo:27017/admin

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongo

  backup:
    image: mongo
    container_name: mongo-backup
    restart: always
    volumes:
      - ./backups:/backup
    depends_on:
      - mongo
    entrypoint: >
      bash -c "
        mkdir -p /backup &&
        while true; do
          TIMESTAMP=$(date +%F-%T);
          mongodump --host mongo --username admin --password password --out /backup/$TIMESTAMP;
          echo '✅ Backup done at $TIMESTAMP';
          sleep 3600;
        done
      "

volumes:
  mongo-data:
