apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: tvibe/webapp:SIT737
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://admin:password@mongodb-service:27017/admin"  # Correct MongoDB URI
